name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Create and use multi-platform builder
        run: |
          docker buildx create --use --name builder --platform linux/amd64,linux/arm64
          docker buildx inspect --bootstrap
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./spec/pom.xml
          mvn clean package -f ./order/pom.xml
          mvn clean package -f ./marketing/pom.xml
          mvn clean package -f ./insurance/pom.xml
          mvn clean package -f ./payment/pom.xml
          mvn clean package -f ./salesdashboard/pom.xml
          mvn clean package -f ./customer/pom.xml

      - name: Set lowercase names to use in tags
        run: |
          echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REF_NAME=$(echo ${{ github.ref_name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Docker Build and push for Spec
        uses: docker/build-push-action@v4
        with:
          context: ./spec
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/spec:latest
            ghcr.io/${{ env.REPO_NAME }}/spec:${{ env.REF_NAME }}
            
      - name: Docker Build and push for Order
        uses: docker/build-push-action@v4
        with:
          context: ./order
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/order:latest
            ghcr.io/${{ env.REPO_NAME }}/order:${{ env.REF_NAME }}
            
      - name: Docker Build and push for Marketing
        uses: docker/build-push-action@v4
        with:
          context: ./marketing
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/marketing:latest
            ghcr.io/${{ env.REPO_NAME }}/marketing:${{ env.REF_NAME }}
            
      - name: Docker Build and push for Insurance
        uses: docker/build-push-action@v4
        with:
          context: ./insurance
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/insurance:latest
            ghcr.io/${{ env.REPO_NAME }}/insurance:${{ env.REF_NAME }}
            
      - name: Docker Build and push for Payment
        uses: docker/build-push-action@v4
        with:
          context: ./payment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/payment:latest
            ghcr.io/${{ env.REPO_NAME }}/payment:${{ env.REF_NAME }}
            
      - name: Docker Build and push for Salesdashboard
        uses: docker/build-push-action@v4
        with:
          context: ./salesdashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/salesdashboard:latest
            ghcr.io/${{ env.REPO_NAME }}/salesdashboard:${{ env.REF_NAME }}
            
      - name: Docker Build and push for Customer
        uses: docker/build-push-action@v4
        with:
          context: ./customer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/customer:latest
            ghcr.io/${{ env.REPO_NAME }}/customer:${{ env.REF_NAME }}
            

      - name: Update Kubernetes manifests
        run: |
          sed -i '/name: "spec"/{N;s|image: "ghcr.io/[^"]*"|image: "ghcr.io/${{ env.REPO_NAME }}/spec:${{ env.REF_NAME }}"|}' ./kubernetes/template/template.yml
          sed -i '/name: "order"/{N;s|image: "ghcr.io/[^"]*"|image: "ghcr.io/${{ env.REPO_NAME }}/order:${{ env.REF_NAME }}"|}' ./kubernetes/template/template.yml
          sed -i '/name: "marketing"/{N;s|image: "ghcr.io/[^"]*"|image: "ghcr.io/${{ env.REPO_NAME }}/marketing:${{ env.REF_NAME }}"|}' ./kubernetes/template/template.yml
          sed -i '/name: "insurance"/{N;s|image: "ghcr.io/[^"]*"|image: "ghcr.io/${{ env.REPO_NAME }}/insurance:${{ env.REF_NAME }}"|}' ./kubernetes/template/template.yml
          sed -i '/name: "payment"/{N;s|image: "ghcr.io/[^"]*"|image: "ghcr.io/${{ env.REPO_NAME }}/payment:${{ env.REF_NAME }}"|}' ./kubernetes/template/template.yml
          sed -i '/name: "salesdashboard"/{N;s|image: "ghcr.io/[^"]*"|image: "ghcr.io/${{ env.REPO_NAME }}/salesdashboard:${{ env.REF_NAME }}"|}' ./kubernetes/template/template.yml
          sed -i '/name: "customer"/{N;s|image: "ghcr.io/[^"]*"|image: "ghcr.io/${{ env.REPO_NAME }}/customer:${{ env.REF_NAME }}"|}' ./kubernetes/template/template.yml
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name "${{ github.actor }}"
          git add ./kubernetes/template/template.yml
          git commit -m "Update image tag to ${{ env.REF_NAME }}"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
