server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: spec
          uri: http://localhost:8082
          predicates:
            - Path=/specComparations/**, /specs/**, 
        - id: order
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**, 
        - id: marketing
          uri: http://localhost:8084
          predicates:
            - Path=/retargettings/**, 
        - id: insurance
          uri: http://localhost:8085
          predicates:
            - Path=/insuranceSubscriptions/**, 
        - id: payment
          uri: http://localhost:8086
          predicates:
            - Path=/payments/**, 
        - id: salesdashboard
          uri: http://localhost:8087
          predicates:
            - Path=salesStatuses/**, 
        - id: customer
          uri: http://localhost:8089
          predicates:
            - Path=/customers/**, /messages/**, 
        - id: frontend
          uri: http://localhost:8081
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: spec
          uri: http://spec:8080
          predicates:
            - Path=/specComparations/**, /specs/**, 
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: marketing
          uri: http://marketing:8080
          predicates:
            - Path=/retargettings/**, 
        - id: insurance
          uri: http://insurance:8080
          predicates:
            - Path=/insuranceSubscriptions/**, 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: salesdashboard
          uri: http://salesdashboard:8080
          predicates:
            - Path=, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/customers/**, /messages/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
